config/routes.rb
Rails.application.routes.draw do
  root "articles#index"
  # users
  match "signup", :to => 'users#create', :via => 'post'
  get "signup", to: "users#new"
  # session
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "login", to: "sessions#destroy"
  # resources
  resources :users, except: [:new]
  resources :articles
  resources :categories, except: [:destroy, :edit]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true
  validates :content, presence: true, length: { minimum: 12 }
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true,
                   uniqueness: { case_sensitive: false },
                   length: { minimum: 3, maximum: 25 }
end

app/models/user.rb
class User < ApplicationRecord
  before_save :downcase_email
  has_many :articles, dependent: :destroy
  has_secure_password
  validates :username, presence: true,
                        length: { minimum: 3, maximum: 25 },
                        uniqueness: { case_sensitive: false }
  validates :email, presence: true,
                      length: { maximum: 105 },
                      format: { with: URI::MailTo::EMAIL_REGEXP },
                      uniqueness: { case_sensitive: false }

  private
  def downcase_email
    self.email = email.downcase
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:warning] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_authorized_user, only: [:edit, :update, :destroy]

  def index
    @articles = Article.all()
  end

  def show
  end

  def create
    @article = Article.new(receive_article_params)
    @article.user = current_user
    if @article.save && @article.user
      flash[:success] = "Article was created successfully."
      redirect_to(@article)
    else
      render :new
    end
  end

  def new
    @article = Article.new()
  end

  def edit
  end

  def update
    if @article.update(receive_article_params)
      flash[:success] = "Article was edited successfully."
      redirect_to(@article)
    else
      render :edit
    end
  end

  def destroy
    @article.destroy()
    flash[:success] = "Article was deleted successfully."
    redirect_to articles_path, status: :see_other
  end

  private
  def set_article
    @article = Article.find(params[:id])
  end

  def receive_article_params
    params.require(:article).permit(:title, :content)
  end

  def require_authorized_user
    if current_user != @article.user && !current_user.admin?
      flash[:warning] = "You are not allowed to perform that action"
      redirect_to @article
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :require_admin, except: [:index, :show]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Category was succesfully created"
      redirect_to @category
    else
      render :new
    end
  end

  def show
    @category = Category.find(params[:id])

  end

  # def destroy
  # end

  # def edit
  # end

  private
  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !(logged_in? && current_user.admin?)
      flash[:warning] = "You are not allowed to perform that action"
      redirect_to categories_path
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to articles_path
    else
      flash.now[:danger] = "There was something wrong with your login details."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "Logged out successfully."
    redirect_to articles_path, status: :see_other
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:show, :edit, :update, :destroy]
  before_action :require_authorized_user, only: [:edit, :update, :destroy]

  def index
    @users = User.all()
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Account information was edited successfully."
      redirect_to @user
    else
      render :edit
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:primary] = "User was created successfully. Welcome #{@user.username}!"
      redirect_to articles_path
    else
      render :new
    end
  end

  def destroy
    @user.destroy
    if !current_user.admin?
      session[:user_id] = nil
    end
    flash[:success] = "User deleted successfully."
    redirect_to articles_path, status: :see_other
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def require_authorized_user
    if current_user != @user && !current_user.admin?
      flash[:warning] = "You are not allowed to perform that action"
      redirect_to @user
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def random_avatar_for_user(user, options = { size: 200 })
    src = "https://i.pravatar.cc/#{options[:size]}"
    image_tag(src, alt: user.username, class: "rounded shadow mx-auto d-block")
  end

  def get_random_article_background_image
    "https://source.unsplash.com/random/?article"
  end
end

app/views/articles/_form.html.erb
<%= form_with(model: @article, data: { turbo: false }) do |f| %>
  <legend class="text-center py-2 my-2">
    <h3 class="display-4">
      <%= @article.new_record? ? "Creating new article" : "Editing an article" %>
    </h3>
  </legend>
  <fieldset>
    <div class="mb-3 w-50 mx-auto">
      <%= f.label :title, class: "mx-auto form-label" %>
      <%= f.text_field :title, size:32, autofocus:true, placeholder: "Enter article title", class: "form-control" %>
    </div>
    <div class="mb-3 w-50 mx-auto">
      <%= f.label :content, class: "mx-auto form-label" %>
      <%= f.text_area :content, size:"0x10", wrap:"soft", placeholder: "Put your content here", class: "form-control" %>
    </div>
    <div class="mb-3 w-50 mx-auto">
      <%= f.submit @article.new_record? ? "Create article" : "Save", class: "btn btn-primary" %>
      <% if !@article.new_record? %>
        <%= link_to "Delete", article_path(@article), class:"btn btn-danger", data: { "turbo-method": :delete, "turbo-confirm": "Are you sure?" } %>
      <% end %>
    </div>
  </fieldset>
<% end %>

app/views/articles/edit.html.erb
<main>
  <%= render 'shared/errors', obj: @article %>
  <%= render 'form' %>
  <div class="mb-3 w-50 mx-auto">
    <%= link_to "Cancel and back to articles list", articles_path, class: "btn btn-outline-secondary" %>
  </div>
</main>
<br>

app/views/articles/index.html.erb
<main>
  <section class="text-center position-relative" style="height: 400px; background: center no-repeat url(https://source.unsplash.com/random/?article,text);" >
    <h1 class="shadow-sm p-3 mb-5 bg-body rounded py-3 px-5 display-5 fw-bold position-absolute top-50 start-50 translate-middle">
    Articles
      <p class="lead position-relative">
        Feel free to check our articles
      </p>
    </h1>
  </section>

  <div class="w-75 mx-auto" style="max-width: 500px; border: .1px black solid; opacity: 15% "></div>

  <% if @articles.empty? %>
    <div style="min-height: 150px; display: flex; justify-content: center; align-items: center;">
      <h3 class="lead opacity-50 my-4 text-center">There are no articles. Would you like to add one?</h3>
    </div>
  <% end %>

  <section class="my-2 text-center">
    <dl>
      <% @articles.reverse_each do |a| %>
        <article class="card px-2 py-2 my-5" style="max-width: 70%; margin: 0 auto;">

          <section class="card-header">
            <h2 class="card-title">
              <%= a.title.truncate(52) %>
            </h2>
            <h3 class="card-subtitle opacity-50 text-black-50">
              by: <%= link_to "#{a.user.username}", user_path(a.user) %>
            </h3>
          </section>

          <section class="card-body w-75 mx-auto">
            <p class="card-text">
              <%= a.content.truncate(352) %>
            </p>
          </section>

          <section class="card-footer py-2 my-2">
            <%= link_to "Show", article_path(a), class:"btn btn-outline-primary" %>
            <% if logged_in? && (current_user == a.user || current_user.admin?)  %>
              <%= link_to "Edit", edit_article_path(a), class:"btn btn-outline-success" %>
              <%= link_to "Delete", article_path(a), class:"btn btn-outline-danger", data: { "turbo-method": :delete, "turbo-confirm": "Are you sure?" } %>
            <% end %>
          </section>

          <section class="card-footer py-2 my-2">
            <%= distance_of_time_in_words_to_now(a.created_at) %> ago
          </section>

        </article>

        <div class="w-25 mx-auto" style="max-width: 500px; border: .1px black solid; opacity: 15% "></div>

      <% end %>
    </dl>
  </section>

</main>
<nav class="px-4 py-2 my-4 text-center">
  <%= link_to "Create new article", new_article_path, class: "btn btn-outline-primary" %>
</nav>

app/views/articles/new.html.erb
<main>
  <%= render 'shared/errors', obj: @article %>
  <%= render 'form' %>
  <div class="mb-3 w-50 mx-auto">
    <%= link_to "Cancel and back to articles list", articles_path, class: "btn btn-outline-secondary" %>
  </div>
</main>

app/views/articles/show.html.erb
<main class="px-4 my-4 py-4 text-center card">
  <div class="card-header">
    <h1 class="card-title py-2">
      <%= @article.title %>
    </h1>
    <h4 class="card-subtitle py-2">
      Created by <%= link_to @article.user.username, user_path(@article.user) %>
    </h4>
  </div>

  <section class="card-body">
    <p class="card-text py-2 w-50 mx-auto">
      <%= @article.content %>
    </p>
  </section>

  <div class="card-footer">
    <p class="w-50 mx-auto">
      <%= distance_of_time_in_words_to_now(@article.created_at) %> ago
    </p>
  </div>
</main>

<section class="px-4 py-2 my-4 text-center">
  <%= link_to "Back to article list", articles_path, class:"btn btn-outline-primary" %>
  <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
    <%= link_to "Edit", edit_article_path(@article), class:"btn btn-outline-success" %>
    <%= link_to "Delete", article_path(@article), class:"btn btn-outline-danger", data: { "turbo-method": :delete, "turbo-confirm": "Are you sure?" } %>
  <% end %>
</section>

app/views/categories/index.html.erb
<main>
    <h1 class="display-4 p-4 m-4 text-center" >
      Categories
    </h1>
  <ul class="text-center list-group">
    <% @categories.each do |category| %>
      <li class="list-group-item">
        <div>
          <strong>
            <%= link_to category.name, category, class: "lead" %>
          </strong>
        </div>
      </li>
    <% end %>
  </ul>
</main>
<nav class="px-4 py-2 my-4 text-center">
  <%= link_to "Back to articles list", articles_path, class: "btn btn-outline-primary" %>
</nav>

app/views/categories/new.html.erb
<main>
  <%= render 'shared/errors', obj: @category %>
  <%= form_with(model: @category, data: { turbo: false }, class: "text-center") do |form| %>
    <fieldset class="my-3">
      <legend class="display-4 mb-2">
        Creating new article
      </legend>
      <div class="mx-auto w-50 form-floating">
        <%= form.text_field :name, placeholder: "Enter a category name", class: "my-4 form-control form-control-lg" %>
        <%= form.label :name, "Category name", class: "form-label" %>
      </div>
    </fieldset>
    <div class="my-4">
      <%= form.submit "Create new category", class: "btn btn-outline-primary"%>
      <%= link_to "Back", articles_path, class: "btn btn-outline-secondary mx-auto" %>
    </div>
  <% end %>
</main>

app/views/categories/show.html.erb
<main>
  <h1 class="display-4 p-4 m-4 text-center">
    <%= @category.name %>
  </h1>
</main>
<nav class="px-4 py-2 my-4 text-center">
  <%= link_to "Back to categories list", categories_path, class:"btn btn-outline-primary" %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogArticles</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head>

  <body>
    <%= render 'shared/nav' %>
    <% flash.each do |name, msg| %>
      <div class="<%= "position-fixed m-2 sticky-bottom bottom-0 end-0 alert alert-#{name} alert-dismissible fade show" %>" style="z-index: 1200;" role="alert" >
        <strong>
          <%= msg %>
        </strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert my-4 text-center rounded w-75 mx-auto">
    <ul class="list-group">
      <% obj.errors.full_messages.each do |error| %>
        <li class="list-group-item list-group-item-danger">
          <%= error %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_nav.html.erb
<nav class="p-3 bg-dark text-white">
  <section class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <h2>
        <%= link_to "ALL ABOUT NOTHING BLOG", root_path, class: "lead text-white", style: "text-decoration: none; "%>
      </h2>
      <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
        <div style="width: 50px"></div>
        <%= link_to "Articles", articles_path, class: "nav-link px-2 text-white" %>
        <%= link_to "Categories", categories_path, class: "nav-link px-2 text-white" %>
        <%= link_to "Users", users_path, class: "nav-link px-2 text-white" %>
        <div style="width: 50px"></div>
        <% if logged_in? %>
        <div class="dropdown">
          <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton2" data-bs-toggle="dropdown" aria-expanded="false">
            Create
          </button>
          <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="dropdownMenuButton2">
            <li>
              <%= link_to "Create new article", new_article_path, class: "dropdown-item" %>
              <% if current_user.admin? %>
                <%= link_to "Create new category", new_category_path, class: "dropdown-item" %>
              <% end %>
            </li>
          </ul>
        </div>
        <% end %>
      </ul>
      <% if logged_in? %>
        <%= link_to current_user.admin? ? "(!A) #{current_user.username}" : current_user.username, user_path(current_user), class: "nav-link px-4 mx-2 lead text-warning" %>
        <%= link_to "Logout", login_path, data: { "turbo-method": :delete }, class: "btn btn-outline-warning" %>
      <% else %>
        <%= link_to "Sign up", signup_path, class: "btn btn-outline-primary mx-2" %>
        <%= link_to "Log in", login_path, class: "btn btn-outline-warning mx-2" %>
      <% end %>
    </div>
  </section>
</nav>

app/views/users/_form.html.erb
<%= form_with(model: @user, url: new ? signup_path : user_path(@user), data: { turbo: false }, class: "text-center" ) do |form| %>
  <fieldset class="bg-light py-3 w-75 mx-auto shadow rounded">
    <legend class="mb-2">
      <h1 class="display-4">
      <%= "Creating new user" if @user.new_record? %>
      </h1>
    </legend>
    <br>
    <div class="mx-auto w-50 form-floating my-3">
      <%= form.text_field :username, class: "form-control form-control-lg", placeholder: "example" %>
      <%= form.label :username, class: "form-label" %>
    </div>
    <div class="mx-auto w-50 form-floating my-3">
      <%= form.email_field :email, class: "form-control form-control-lg" , placeholder: "email@example.com" %>
      <%= form.label :email, class: "form-label" %>
    </div>
    <div class="mx-auto w-50 form-floating my-3">
      <%= form.password_field :password, class: "form-control form-control-lg", placeholder: "secure password" %>
      <%= form.label :password, class: "form-label" %>
    </div>
    <div class="my-4">
      <%= form.submit @user.new_record? ? "Sign up" : "Update account", class: "btn btn-primary"%>
      <%= link_to "Back", articles_path, class: "btn btn-outline-danger mx-auto" %>
    </div>
  </fieldset>
<% end %>

app/views/users/edit.html.erb
<main>
  <header class="text-center py-2 my-2">
    <h1 class="display-5 fw-bold">
    Edit your profile
    </h1>
  </header>
  <%= render 'shared/errors', obj: @user %>
  <%= render partial: 'form', locals: { new: false } %>
</main>

app/views/users/index.html.erb
<main>
    <h1 class="display-4 p-4 m-4 text-center" >
      User list
    </h1>
  <ul class="text-center list-group">
    <% @users.each do |user| %>
      <li class="list-group-item">
        <div>
          <strong>
            <%= link_to user.username, user, class: "lead" %>
          </strong>
          <div class="py-2">
            <% if logged_in? && current_user.admin? %>
              <%= link_to "Delete", user_path(user), class: "p-2 my-1 mx-auto body btn-outline-danger text-decoration-none", data: { "turbo-method": :delete, "turbo-confirm": "Are you sure?" }%>
            <% end %>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
</main>
<nav class="px-4 py-2 my-4 text-center">
  <%= link_to "Back to articles list", articles_path, class: "btn btn-outline-primary" %>
</nav>

app/views/users/new.html.erb
<main>
  <%= render 'shared/errors', obj: @user %>
  <header class="text-center py-2 my-2">
    <h1 class="display-3 fw-bold">
    Sign up
    </h1>
  </header>
  <%= render partial: 'form', locals: { new: true } %>
</main>

app/views/users/show.html.erb
<main class="text-center">

  <% if logged_in? && @user == current_user %>
    <h1 class="my-4" >
    <%= "Hello #{@user.username}! That's your profile" %>
    </h1>
  <% else %>
    <h1 class="my-4" >
      <%= "#{@user.username}'s profile" %>
    </h1>
  <% end %>

  <%= random_avatar_for_user @user %>

  <% if logged_in? && (current_user == @user || current_user.admin?)  %>
    <%= link_to "Edit profile", edit_user_path(@user),  class: "btn btn-warning my-4" %>
    <%= link_to "Delete profile", user_path(@user), class:"btn btn-outline-danger", data: { "turbo-method": :delete, "turbo-confirm": "Are you sure?" } %>
  <% end %>

  <% if logged_in? && @user == current_user %>
    <h2 class="my-4">
      <%= "Your articles:" %>
    </h2>
  <% else %>
    <h2 class="my-4" >
      <%= "#{@user.username}'s articles:" %>
    </h2>
  <% end %>

  <% if @user.articles.empty? %>
    <% if logged_in? && @user == current_user %>
      <p>
        <%= link_to "You have no articles to show.", new_article_path, class: "lead opacity-50 my-4 text-center text-black text-decoration-none" %>
        <br>
        <%= link_to "Make sure you create one today!", new_article_path, class: "lead opacity-50 my-4 text-center text-black text-decoration-none" %>
      </p>
    <% else %>
      <p>User has 0 posts already.</p>
    <% end %>
  <% end %>



  <dl>
    <% @user.articles.each do |a| %>
      <article class="card px-2 py-2 my-5" style="max-width: 70%; margin: 0 auto;">

        <section class="card-header">
          <h2 class="card-title">
            <%= a.title %>
          </h2>
          <h3 class="card-subtitle opacity-50">
            by: <%= link_to "#{a.user.username}", user_path(a.user) %>
          </h3>
        </section>

        <section class="card-body">
          <p class="card-text">
            <%= a.content %>
          </p>
        </section>

        <section class="card-footer py-2 my-2">
          <%= link_to "Show", article_path(a), class:"btn btn-outline-primary" %>
          <% if logged_in? && (current_user == @user || current_user.admin?)  %>
            <%= link_to "Edit", edit_article_path(a), class:"btn btn-outline-success" %>
            <%= link_to "Delete", article_path(a), class:"btn btn-outline-danger", data: { "turbo-method": :delete, "turbo-confirm": "Are you sure?" } %>
          <% end %>
        </section>

      </article>
    <% end %>
  </dl>
</main>
<nav class="px-4 py-2 my-4 text-center">
  <%= link_to "Back to article list", articles_path, class:"btn btn-outline-primary" %>
</nav>